# /swp plus 命令对同一玩家操作的冷却时间(单位: 毫秒，默认值300000为5分钟)
cooldown: 300000
# 以下用于储存
punishments:
  # chat是一个项目名，你可以用英文，也可以用拼音起类似“maren”“zuobi”“shuaping”等名称
  chat:
    # 基本格式为
    # - '违规次数:惩罚命令:撤销该惩罚的命令'
    #   "命令"部分可以填写在服务器后台能够执行的任意命令
    #   命令均是直接通过后台执行，无视权限
    #   ":撤销该惩罚的命令"是可选部分，如果是mute命令不建议填写，因为mute命令的设置、解除是同一个命令，可能会造成错误的禁言
    # 使用{player}替代该玩家的名称
    - 1:tell {player} &c请注意不要骂人！:tell {player} &b我错了冤枉你了…
    - 2:mute {player} 1h
    - 3:mute {player} 1d
    - 4:mute {player}
  # 你可以继续建立项目，例如pvp
  pvp:
    - 1:tempban {player} 1h &c随意攻击其他玩家是不允许的行为:unban {player}
    - 2:ban {player} &c你因多次攻击其他玩家，已被永久封禁:unban {player}