name: StepwisePunishments
main: com.github.spacebang.stepwisepunishments.StepwisePunishments
version: 1.5
commands:
    swp:
        description: 主命令
        usage: |
            §b============阶梯式惩罚插件============
            §b/swp plus <player> <object> [count]- 把玩家<player>在项目<object>上的违规次数增加[count](可选，默认为1)，并自动惩罚
            §b/swp minus <player> <object> [count] - 把玩家<player>在项目<object>上的违规次数减少[count](可选，默认为1)，并自动解除惩罚
            §b/swp see <player> <object> - 查看玩家<player>在项目<object>上的违规次数
            §b/swp reload - 重新加载配置文件